[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "mkdir -p /data/media && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py init_superuser && gunicorn shmoukh_herbal.wsgi:application --bind 0.0.0.0:$PORT"

[[services]]
name = "shmoukh-web"
[[services.ports]]
http = 8000

[[services.volumes]]
source = "shmoukh-media"
target = "/data/media"
