[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "chmod +x startup.sh && ./startup.sh"

[[services]]
name = "shmoukh-web"
[[services.ports]]
http = 8000

[[services.volumes]]
source = "shmoukh-media"
target = "/data/media"
